<template>
  <base-layout page-title="Zmodyfikuj zegar" page-default-back-link="/clocks">
    <clock-form-update
      :clock="loadedClock"
      @modify-clock="modifyClock"
    ></clock-form-update>
  </base-layout>
</template>

<script>
import ClockFormUpdate from "../components/clocks/ClockFormUpdate.vue";
export default {
  data() {
    return {
      clockId: this.$route.params.id
    };
  },
  components: {
    ClockFormUpdate
  },
  methods: {
    async modifyClock(clockData) {
      const clockDataWithId = { id: this.clockId, ...clockData };
      await this.$store.dispatch("modifyClock", clockDataWithId);
      // this is for accessing true item id generated by firebase
      // is this nesessary? NO, not here
      // await this.$store.dispatch("loadClocks");
      this.$router.replace("/clocks/" + this.clockId);
    }
  },
  computed: {
    loadedClock() {
      return this.$store.getters.clock(this.clockId);
    }
  }
};
</script>